version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chained-gt"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gregsomm"
s3_prefix = "chained-gt"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
