AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Required resources for example chained Ground Truth jobs

Globals:
  Function:
    Runtime: python3.7

Parameters:
  S3SourceBucket:
    Type: String
    Description: Enter the name of the S3 bucket that contains the starting images

Resources:
  #######################
  # ROLES
  #######################
  GroundTruthLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSageMakerGroundTruthExecution


  #############################################################################
  # Ground Truth Custom Lambdas
  # (must have "SageMaker" in the name, so corresponding IAM role works)
  #############################################################################
  SageMakerStep1PreLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/pre_step1/src
      Handler: main.lambda_handler
      Role: !GetAtt GroundTruthLambdaRole.Arn

  SageMakerStep1PostLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/post_step1/src
      Handler: main.lambda_handler
      Role: !GetAtt GroundTruthLambdaRole.Arn
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3SourceBucket

  SageMakerStep2PreLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/pre_step2/src
      Handler: main.lambda_handler
      Role: !GetAtt GroundTruthLambdaRole.Arn

  SageMakerStep2PostLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/post_step2/src
      Handler: main.lambda_handler
      Role: !GetAtt GroundTruthLambdaRole.Arn
